# 🧠 Bloc 1 — NumPy : La Pensée Vectorielle

**Objectifs de ce bloc :**
- Comprendre `ndarray`, l'objet central de NumPy.
- Maîtriser les opérations vectorisées pour se passer des boucles `for`.
- Savoir indexer et slicer (découper) des données à 1D et 2D.
- Calculer des statistiques descriptives de base .

In [5]:
import numpy as np

## 1. ndarray — Anatomie d'un tableau NumPy

Le tableau à N dimensions (`ndarray`) est la structure de base. Contrairement aux listes Python, un tableau NumPy contient un seul type de données (`dtype`), ce qui garantit un stockage mémoire contigu et des performances exceptionnelles.

### Création à partir d'une liste Python (1D=1 dimension)

In [6]:
arr_base = np.array([1, 2, 3, 4, 5])
print("Tableau 1D :", arr_base)
print("Type d'objet :", type(arr_base))

Tableau 1D : [1 2 3 4 5]
Type d'objet : <class 'numpy.ndarray'>


### Tableaux pré-remplis de zéros

In [ ]:
# Ici nous créons une matrice (car 2 dimensions) emplit que de zéro
# Note: on donne un tuple comme argument à la fonction
arr_zeros = np.zeros((2, 3))    # 2 lignes, 3 colonnes
print("Zeros (2x3) :\n", arr_zeros)

Zeros (2x3) :
 [[0. 0. 0.]
 [0. 0. 0.]]


### Tableaux pré-remplis de uns

In [8]:
# 4 uns à 1D
arr_ones = np.ones(4)
print("Ones (4) :", arr_ones)

Ones (4) : [1. 1. 1. 1.]


### Séquences numériques à pas fixe (np.arange)

In [9]:
# De 0 à 10 exclus, par pas de 2 (comme range() en Python)
arr_seq = np.arange(0, 10, 2)
print("np.arange :", arr_seq)

np.arange : [0 2 4 6 8]


## 1.1 Observation des arrays
### Inspecter la forme (shape)

In [36]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape (lignes, colonnes) :", arr.shape)

Shape (lignes, colonnes) : (2, 3)


### Inspecter le type de données (dtype)

In [35]:
print("Dtype (type unique des éléments) :", arr.dtype)

Dtype (type unique des éléments) : int64


### Quelques familles de  `dtype` dans NumPy

| Famille | Exemples de `dtype` | Description / Cas d'usage |
| :--- | :--- | :--- |
| **Entiers signés** | `int8`, `int16`, `int32`, `int64` | Entiers positifs ou négatifs. `int8` va de -128 à 127. |
| **Entiers non signés (unsigned)** | `uint8`, `uint16`, `uint32`, `uint64` | Entiers positifs uniquement ($\ge 0$). `uint8` (0 à 255) est très utilisé pour les pixels d'images. |
| **Flottants (décimaux)** | `float16`, `float32`, `float64` | Nombres à virgule. `float32` est le standard pour le Machine Learning / GPU. |

### Inspecter les dimensions et le nombre d'éléments

In [13]:
print("Ndim (dimensions) :", arr.ndim)
print("Size (nombre total d'éléments) :", arr.size)

Ndim (dimensions) : 2
Size (nombre total d'éléments) : 6


### Mini-exercice : à vous !

In [ ]:
# Créez un tableau de 10 éléments valant tous 7
# Astuce : vous pouvez multiplier np.ones() par 7
septs = "FONCTION"
print(septs)

FONCTION


---

## 2. Opérations vectorisées

Oubliez les boucles `for` ! NumPy applique les opérations élément par élément directement. C'est la **vectorisation**.

### Définition des tableaux d'exemple

In [15]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print("a =", a)
print("b =", b)

a = [10 20 30]
b = [1 2 3]


### Addition vectorisée

In [16]:
print("a + b =", a + b)

a + b = [11 22 33]


### Multiplication vectorisée

In [17]:
print("a * b =", a * b)

a * b = [10 40 90]


### Puissance et division

In [18]:
print("b ** 2 =", b ** 2)
print("a / 2 =", a / 2)

b ** 2 = [1 4 9]
a / 2 = [ 5. 10. 15.]


### Fonctions universelles (ufuncs : racine, exp, log)

In [ ]:
print(f"Racine carrée (a) :", np.sqrt(a))
print("Exponentielle (b)  :", np.exp(b))
print("Logarithme (b)     :", np.log(b))

Racine carrée (a) : [3.16227766 4.47213595 5.47722558]
Exponentielle (b)  : [ 2.71828183  7.3890561  20.08553692]
Logarithme (b)     : [0.         0.69314718 1.09861229]


---

## 3. Indexation et slicing avancé

L'indexation et le découpage (`slicing`) en NumPy permettent d'accéder à n'importe quelle partie d'un tableau à 1D ou 2D.

### Définition d'une matrice 2D

In [38]:
matrice = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print("Matrice (3x4) :\n", matrice)

Matrice (3x4) :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Sélectionner un élément précis [ligne, colonne]

In [23]:
# Ligne d'index 1 (2e ligne), colonne d'index 2 (3e colonne)
element = matrice[1, 2]
print("Élément (ligne 1, col 2) :", element)

Élément (ligne 1, col 2) : 7


### Slicing 2D [lignes, colonnes]

In [24]:
# 2 premières lignes (:2), 2 dernières colonnes (2:)
sous_matrice = matrice[:2, 2:]
print("Sous-matrice :\n", sous_matrice)

Sous-matrice :
 [[3 4]
 [7 8]]


---

## 4. Statistiques descriptives & le paramètre `axis`

### Matrice d'exemple

In [27]:
data = np.array([
    [10, 12, 14],
    [20, 22, 24]
])
print("Données :\n", data)

Données :
 [[10 12 14]
 [20 22 24]]


### Moyenne et écart-type globaux

In [28]:
print("Moyenne globale :", np.mean(data))
print("Écart-type     :", np.std(data))

Moyenne globale : 17.0
Écart-type     : 5.259911279353167


### Minimum et Maximum globaux

In [29]:
print("Min / Max :", np.min(data), "/", np.max(data))

Min / Max : 10 / 24


### Calcul par colonne (axis=0)

In [30]:
# axis=0 : effondre les lignes -> calcul par COLONNE
print("Moyenne par colonne (axis=0) :", np.mean(data, axis=0))

Moyenne par colonne (axis=0) : [15. 17. 19.]


### Calcul par ligne (axis=1)

In [31]:
# axis=1 : effondre les colonnes -> calcul par LIGNE
print("Moyenne par ligne (axis=1) :", np.mean(data, axis=1))

Moyenne par ligne (axis=1) : [12. 22.]


---

# Exercices pratiques

## 🏋️ Exercice 1.1 — Le Thermomètre

**Instructions :**
Chargez `../01_data/exercises/temperatures_365.csv` et extrayez la colonne 'temperature' sous forme de tableau NumPy.
Effectuez les calculs **SANS AUCUNE BOUCLE `for`**.

In [40]:
# 1. Chargement des données (on verra pandas plus en détails durant les prochains modules)
import pandas as pd
df_temp = pd.read_csv("../01_data/exercises/temperatures_365.csv")
type(df_temp)

pandas.DataFrame

In [ ]:
# df_temp est un dataframe; nous allons convertir en Numpay array
temps = df_temp["temperature"].values  # Extraction sous forme d'array NumPy
print(f"Nombre de jours : {len(temps)} \n Le type la variable 'temps'est {type(temps)}")

Nombre de jours : 365 
 -Le type la variable 'temps'est <class 'numpy.ndarray'>


In [ ]:
# Q1 : Calculez la moyenne et l'écart-type des températures
moyenne = "FONCTION"
ecart_type = "FONCTION"
print(f"Moyenne : {moyenne:.2f}°C | Écart-type : {ecart_type:.2f}°C")   # on peut aussi utiliser la fonction round()

ValueError: Unknown format code 'f' for object of type 'str'

In [ ]:
# Q2 : Nombre de jours de canicule (température > 35°C)
nb_canicule = "FONCTION"
print(f"Jours de canicule (> 35°C) : {nb_canicule}")

In [ ]:
# Q3 : Nombre de jours de gel (température < 0°C)
nb_gel = "FONCTION"
print(f"Jours de gel (< 0°C) : {nb_gel}")

In [ ]:
# Q4 : Quel est le numéro du jour le plus chaud (index/argmax) et sa température ?
jour_max = temps.argmax()
temp_max = temps.max()
print(f"Jour le plus chaud : Jour n°{jour_max + 1} avec {temp_max}°C")

## 🏋️ Exercice 1.2 — La Matrice de Notes

**Instructions :**
Générez une matrice de 30 élèves × 5 matières avec des notes entre 0 et 20. \n
on utilise la fonction `np.random.default_rng(42)` pour générer des valeurs aléatoires

In [ ]:
# 1. Génération de la matrice
rng = np.random.default_rng(42)     # 42 est une valeur conventionelle appelé seed.
notes = rng.uniform(0, 20, size=(30, 5)).round(1)
print("Extrait des notes (5 premiers élèves) :\n", notes[:5])

Extrait des notes (5 premiers élèves) :
 [[15.5  8.8 17.2 13.9  1.9]
 [19.5 15.2 15.7  2.6  9. ]
 [ 7.4 18.5 12.9 16.5  8.9]
 [ 4.5 11.1  1.3 16.6 12.6]
 [15.2  7.1 19.4 17.9 15.6]]


In [ ]:
# Q1 : Moyenne par élève (axis=1)
# Votre code ici

In [ ]:
# Q2 : Moyenne par matière (axis=0)
# Votre code ici

In [ ]:
# Q3 : Élèves avec moyenne > médiane globale
# Votre code ici

In [ ]:
# Q4 : Matière avec la plus forte variance (np.var sur axis=0)
# Votre code ici

## 🏋️ Exercice 1.3 — Benchmark Python vs NumPy

**Instructions :**
Chargez `sale_price` de `../01_data/exercises/thelook_sales.csv` en liste Python et en array NumPy. Comparez les temps de calcul.

In [ ]:
import pandas as pd

df_sales = pd.read_csv("../01_data/exercises/thelook_sales.csv")

prix_liste = df_sales["sale_price"].tolist()        # on retourne une provenant dúne colonne d'un dataframe
prix_array = df_sales["sale_price"].to_numpy()      # ici, on convertit
print(f"Nombre d'éléments : {len(prix_liste)}")

prix_array.shape

Nombre d'éléments : 50000


(50000,)

In [ ]:
import timeit

> 💡 **Règle Jupyter :**
> - `%` (**Line Magic**) : S'applique uniquement à **une seule ligne** de code.
> - `%%` (**Cell Magic**) : S'applique à **l'ensemble de la cellule** (doit impérativement se trouver sur la **toute première ligne** de la cellule). 

> - Nous allons l'utiliser pour mesurer le temps d'execution au sein de notre cellule

In [ ]:
%%timeit

# Mesure 1 : Boucle for Python
total = 0
for p in prix_liste:
    total += p

745 μs ± 8.74 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [70]:
%%timeit

# Mesure 2 : sum() natif Python
total = sum(prix_liste)

155 μs ± 3.05 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [71]:
%%timeit

# Mesure 3 : np.sum() NumPy
total = np.sum(prix_array)

13.4 μs ± 153 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


**/!\ N'utiliser pas la function python standard sum() dans Numpy, mais bien np.sum() !**